apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iopeer.fullname" . }}-secrets
  labels:
    {{- include "iopeer.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: encryption-key
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iopeer.fullname" . }}-jwt-secret
  labels:
    {{- include "iopeer.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: jwt-secret
    secret-generator.v1.mittwald.de/length: "64"
type: Opaque
data: {} 