name: CI
on:
  push: { branches: ["main","develop"] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 9 }
      - run: pnpm install
      - run: pnpm turbo run lint || true
      - run: pnpm turbo run build
